### ISSUE TITLE
Errors in installing software

### ISSUE THREAD

**Issue by ahmedmagdy95** [satya164/fedy#170]
Brackets doesn't install and says Error, Atom installed successfully but without an icon and google chrome doesn't launch from the same icon it launches from google-chrome-stable or something

**Comment by satya164** [comment]
The Brackets repo is not present for Fedora 22. If the author doesn't update his repo after Fedora 22's release, I'll fix the plugin.

The Google Chrome issue is well known and a problem with Google Chrome itself (someone said it was happening because of different window class and desktop file name). Nothing Fedy can do.

I'll check the issue with Atom.

**Comment by satya164** [comment]
Also, Atom is installed from this copr - https://copr.fedoraproject.org/coprs/helber/atom

It would be better to report the issue to the original author of the package.
